import { Result } from "../../core/models/Result"

export type ReadResultEntity = {
    id: number,
    source_id: number,
    roi_side: string,
    roi_description: string,
    roi_mask: string,
    roi_mask_conversion_method: string,
    stim_params_stated: number,
    stim_amp_ma_min: number,
    stim_amp_ma_max: number,
    stim_amp_ma_avg: number,
    stim_amplitude_variable: number,
    stim_freq: number,
    stim_freq_max: number,
    stim_frequency_multiple: string,
    stim_duration: number,
    stim_duration_max: number,
    stim_duration_multiple: string,
    stim_electrode_make: string,
    stim_implantation_type: string,
    stim_contact_separation: number,
    stim_contact_diameter: number,
    stim_contact_length: number,
    stim_phase_length: number,
    stim_phase_type: string,
    stim_epi_zone: string,
    stim_epi_zone_comments: string,
    effect_class: string,
    effect_descriptor: string,
    effect_details: string,
    effect_post_discharge: string,
    effect_lateralization: string,
    effect_dominant: string,
    effect_body_part: string,
    effect_comments: string,
    task_category: string,
    task_subcategory: string,
    task_characteristic: string,
    task_comments: string,
    function_category: string,
    function_subcategory: string,
    function_characteristic: string,
    function_stated: number,
    function_comments: string,
    occurrence_clinical_effect: number,
    nb_stimulations: number,
    occurrence_ns: number,
    complement_parameters: number,
    complement_parameters_result_id: number,
    occurrence_responsive_rate: number,
    comments: string,
    comments_2: string,
    clinical_semiology: string,
    source_db?: string
}

export const ReadResultEntityToModel = (readEntity: ReadResultEntity): Result => {
    return {
        id: readEntity.id,
        source_id: readEntity.source_id,
        roi: {
            side: readEntity.roi_side,
            description: readEntity.roi_description,
            mask: readEntity.roi_mask,
            mask_conversion_method: readEntity.roi_mask_conversion_method,
        },
        stimulation_parameters: {
            stated: readEntity.stim_params_stated > 0,
            amplitude_ma_min: readEntity.stim_amp_ma_min,
            amplitude_ma_max: readEntity.stim_amp_ma_max,
            amplitude_ma_avg: readEntity.stim_amp_ma_avg,
            amplitude_variable: readEntity.stim_amplitude_variable > 0,
            frequency_hz: readEntity.stim_freq,
            frequency_hz_max: readEntity.stim_freq_max,
            frequency_multiple: readEntity.stim_frequency_multiple,
            duration_s: readEntity.stim_duration,
            duration_s_max: readEntity.stim_duration_max,
            duration_multiple: readEntity.stim_duration_multiple,
            electrode_make: readEntity.stim_electrode_make,
            implantation_type: readEntity.stim_implantation_type,
            contact_separation: readEntity.stim_contact_separation,
            contact_diameter: readEntity.stim_contact_diameter,
            contact_length: readEntity.stim_contact_length,
            phase_length: readEntity.stim_phase_length,
            phase_type: readEntity.stim_phase_type,
            epi_zone: readEntity.stim_epi_zone,
            epi_zone_comments: readEntity.stim_epi_zone_comments,
        },
        effect: {
            class: readEntity.effect_class,
            descriptor: readEntity.effect_descriptor,
            details: readEntity.effect_details,
            post_discharge: readEntity.effect_post_discharge,
            lateralization: readEntity.effect_lateralization,
            dominant: readEntity.effect_dominant,
            body_part: readEntity.effect_body_part,
            comments: readEntity.effect_comments
        },
        task: {
            category: readEntity.task_category,
            subcategory: readEntity.task_subcategory,
            characteristic: readEntity.task_characteristic,
            comments: readEntity.task_comments
        },
        function: {
            category: readEntity.function_category,
            subcategory: readEntity.function_subcategory,
            characteristic: readEntity.function_characteristic,
            stated: readEntity.function_stated > 0,
            comments: readEntity.function_comments
        },
        occurrence_clinical_effect: readEntity.occurrence_clinical_effect,
        nb_stimulations: readEntity.nb_stimulations,
        occurrence_ns: readEntity.occurrence_ns > 0,
        complement_parameters: readEntity.complement_parameters > 0,
        complement_parameters_result_id: readEntity.complement_parameters_result_id,
        occurrence_responsive_rate: readEntity.occurrence_responsive_rate > 0,
        comments: readEntity.comments,
        comments_2: readEntity.comments_2,
        clinical_semiology: readEntity.clinical_semiology,
        source_db: readEntity.source_db
    }
}