// ddo = data display object
export interface ResultDdo {
    id: number,
    roi: {
        side: string,
        description: string,
        mask: string,
        mask_conversion_method: string,
    },
    stimulation_parameters: {
        stated: boolean,
        amplitude_ma_min: number,
        amplitude_ma_max: number,
        amplitude_ma_avg: number,
        frequency_hz: number,
        frequency_hz_max: number,
        duration_s: number,
        duration_s_max: number,
        electrode_make: string,
        implantation_type: string,
        contact_separation: number,
        contact_diameter: number,
        contact_length: number,
        phase_length: number,
        phase_type: string,
        epi_zone: string,
        epi_zone_comments: string,
    }
    effect: {
        class: string,
        descriptor: string,
        details: string,
        post_discharge: string,
        lateralization: string,
        dominant: string,
        body_part: string,
        comments: string,
    },
    task: {
        category: string,
        subcategory: string,
        characteristic: string,
        comments: string,
    },
    function: {
        category: string,
        subcategory: string,
        characteristic: string,
        stated: boolean,
        comments: string,
    },
    occurrence_clinical_effect: number,
    nb_stimulations: number,
    occurrence_ns: boolean,
    complement_parameters: boolean,
    complement_parameters_result_id: number,
    occurrence_responsive_rate: boolean,
    comments?: string,
    comments_2?: string,
    source_db?: string,
    clinical_semiology: string,
}