name: Build
on: [push, pull_request]

jobs:
  build_on_win:
    runs-on: windows-latest
    env:
      working-directory: ./app
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      working-directory: ${{env.working-directory}}
      run: npm install
    - name: build
      working-directory: ${{env.working-directory}}
      run: npm run make